### ISSUE TITLE
Failed to launch demo on Windows

### ISSUE THREAD

**Issue by LXYan2333** [bolinfest/monaco-tm#40]
Failed to launch demo on windows, but succeed to launch on Ubuntu WSL.

Step to reproduce:

1. clone this repo to a Windows PC.
2. yarn install
3. yarn demo
4. notice the demo won't launch
5. open this directory in a Ubuntu WSL and launch it, notice it launchs.

Log in windows:
```
PS C:\Users\lxyan\programs\vscode-ext\monaco-tm> yarn install
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.49s.
PS C:\Users\lxyan\programs\vscode-ext\monaco-tm> yarn demo   
yarn run v1.22.19
$ webpack-dev-server --config webpack.config.cjs --port 8084
i ｢wds｣: Project is running at http://localhost:8084/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\lxyan\programs\vscode-ext\monaco-tm
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (C:\Users\lxyan\programs\vscode-ext\monaco-tm\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\lxyan\programs\vscode-ext\monaco-tm\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\lxyan\programs\vscode-ext\monaco-tm\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\lxyan\programs\vscode-ext\monaco-tm\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\lxyan\programs\vscode-ext\monaco-tm\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\lxyan\programs\vscode-ext\monaco-tm\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\lxyan\programs\vscode-ext\monaco-tm\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\lxyan\programs\vscode-ext\monaco-tm\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\lxyan\programs\vscode-ext\monaco-tm>
```

**Comment by LXYan2333** [comment]
Maybe it is due to node version?
On my windows:
```
PS C:\Users\lxyan\programs\vscode-ext\monaco-tm> node --version
v19.1.0
```

On my Ubuntu WSL:
```
lxyan@EliteBook-845:~$ node --version
v12.22.9
```
