### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by jiapei100** [bolinfest/monaco-tm#45]
I'm trying to run the demo under **Ubuntu 22.04**, with **npm**:

``console
➜  monaco-tm git:(main) npm --version
9.7.1
```

But got the following **ERROR** messages:

```console
➜  monaco-tm git:(main) yarn demo
yarn run v1.22.19
warning ../../../package.json: No license field
$ webpack-dev-server --config webpack.config.cjs --port 8084
ℹ ｢wds｣: Project is running at http://localhost:8084/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ....../monaco-tm
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (....../monaco-tm/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (....../monaco-tm/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (....../monaco-tm/node_modules/webpack/lib/NormalModule.js:471:10)
    at ....../monaco-tm/node_modules/webpack/lib/NormalModule.js:503:5
    at ....../monaco-tm/node_modules/webpack/lib/NormalModule.js:358:12
    at ....../monaco-tm/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (....../monaco-tm/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (....../monaco-tm/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JulianCataldo** [comment]
Fix: 

```sh
NODE_OPTIONS=--openssl-legacy-provider npm run demo
```

Source:
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
